# Generated by Django 2.1 on 2018-12-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commented_article', to='webapp.Article', verbose_name='Комментируемая статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commented_by', to='webapp.User', verbose_name='Прокомментировал')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commented_comment', to='webapp.Comment', verbose_name='Комментируемый комментарий')),
            ],
        ),
    ]
